// <auto-generated />
using System;
using GeoFoto.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GeoFoto.Api.Migrations
{
    [DbContext(typeof(GeoFotoDbContext))]
    partial class GeoFotoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GeoFoto.Api.Models.Foto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("FechaTomada")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("LatitudExif")
                        .HasColumnType("decimal(10,7)");

                    b.Property<decimal?>("LongitudExif")
                        .HasColumnType("decimal(10,7)");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<int>("PuntoId")
                        .HasColumnType("int");

                    b.Property<string>("RutaFisica")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("TamanoBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("PuntoId")
                        .HasDatabaseName("IX_Fotos_PuntoId");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("IX_Fotos_UpdatedAt");

                    b.ToTable("Fotos", (string)null);
                });

            modelBuilder.Entity("GeoFoto.Api.Models.Punto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<decimal>("Latitud")
                        .HasColumnType("decimal(10,7)");

                    b.Property<decimal>("Longitud")
                        .HasColumnType("decimal(10,7)");

                    b.Property<string>("Nombre")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("IX_Puntos_UpdatedAt");

                    b.HasIndex("Latitud", "Longitud")
                        .HasDatabaseName("IX_Puntos_Lat_Lng");

                    b.ToTable("Puntos", (string)null);
                });

            modelBuilder.Entity("GeoFoto.Api.Models.Foto", b =>
                {
                    b.HasOne("GeoFoto.Api.Models.Punto", "Punto")
                        .WithMany("Fotos")
                        .HasForeignKey("PuntoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Punto");
                });

            modelBuilder.Entity("GeoFoto.Api.Models.Punto", b =>
                {
                    b.Navigation("Fotos");
                });
#pragma warning restore 612, 618
        }
    }
}
